pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url 'https://maven.fabricmc.net/' }
    }
}

rootProject.name = 'VeloAirChat'

include ':common'
include ':protocol'
include ':velocity'
include ':paper'
include ':fabric'

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_PROJECT)
    repositories {
        mavenCentral()
        maven { url 'https://repo.extendedclip.com/content/repositories/placeholderapi/' }
        exclusiveContent {
            forRepository {
                maven { url 'https://repo.mikeprimm.com/' }
            }
            filter {
                includeGroup 'us.dynmap'
            }
        }
        maven { url 'https://maven.fabricmc.net/' }
        maven { url 'https://repo.papermc.io/repository/maven-public/' }
        maven { url 'https://repo.papermc.io/repository/maven-snapshots/' }
    }
}
